### ISSUE TITLE
Add global hub robot credentials to values

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/node-deployment#14]
Currently, both the message broker and the hub adapter use robot credentials generated in the Hub UI. Instead of passing these credentials twice, they should be passed once using a `global: ` value. this will require modifying both of the individual subcharts to utilize these values.

**Comment by brucetony** [comment]
Global variables have been added to the helm charts that need hub access. Each node deployment can use the same robot credentials i.e. one robot account per node instance. Ideally, the hub website will have a button that will allow a user to download a yaml file with the robot credentials in the following format:
```yaml
global:
  hubAuth:
    robotUser: "myRobotUser"
    robotSecret: "somealphanumericrandomlygeneratedpassword"
```
users can then use this file when deploying a node instance to apply the obtained credentials to the relevant services using: `helm install myInstance flame-node -f robot_credentials.yaml`. This should be the only external information they need to deploy the node services
